# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('car', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('booking_start', models.DateTimeField(verbose_name='Booking start time')),
                ('booking_end', models.DateTimeField(verbose_name='Booking end time')),
                ('used_start', models.DateTimeField(verbose_name='Usage start time')),
                ('used_end', models.DateTimeField(verbose_name='Usage end time')),
                ('distance', models.IntegerField()),
                ('max_speed', models.IntegerField(verbose_name='Maximum speed')),
                ('sudden_accel', models.IntegerField(verbose_name='Number of sudden accelerations')),
                ('sudden_decel', models.IntegerField(verbose_name='Number of sudder decelerations')),
                ('time_charge', models.IntegerField(verbose_name='Usage time charge')),
                ('distance_charge', models.IntegerField(verbose_name='Driven distance charge')),
                ('penalty_charge', models.IntegerField(verbose_name='Late return penalty charge')),
                ('insurance_charge', models.IntegerField()),
                ('total_charge', models.IntegerField()),
            ],
        ),
    ]
