# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesdata', '0003_auto_20160421_0318'),
        ('bookings', '0002_auto_20160421_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesdata.Station'),
        ),
    ]
