# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.IntegerField(default=0, help_text='Always a negative amount'),
            preserve_default=False,
        ),
    ]
