# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='timesdata.Station'),
        ),
    ]
